# ===============================
# tomcat 配置, 配合nginx
# ===============================
server:
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
    
  # 监听端口
  port: 8080

# ===============================
# spring配置
# ===============================
spring:
  freemarker:
    # 模板后缀
    suffix: .html
    # 特殊配置: 防止freemark空指针
    settings: 
      "[classic_compatible]": true

  # 特殊配置: 防止没有定义接口的aop类出错
  aop.proxy-target-class: true

  # sping 2.x版默认是关闭jmx的，需要手动打开
  jmx:
    enabled: true

  # 文件上传配置
  servlet:
    multipart:
      maxRequestSize: 2000MB
      maxFileSize: 2000MB


# ===============================
# Logger配置 注意：Eclipse需要装ansi颜色插件，因为日志格式带了颜色
# ===============================
logging:
  #register-shutdown-hook: true
  level:
    # root是全局的，默认是error
    root: info
    # 我们一般打开框架的info日志，方便检查
    # com.cherry.jeeves: info
    # ActionInfo开了debug日志后，可以看到每个请求的参数和响应时间
    #"[com.liangwj.jeeves]": ${APP_LOG_LEVEL:debug}
    # 本项目的代码默认是debug
    "[com.liangwj.jeeves]": ${APP_LOG_LEVEL:debug}
    "[com.liangwj.tools2k.utils.net.FileCookieStore]": ${APP_LOG_LEVEL:debug}
    
  # 在console中显示时，我们为字体加了颜色，方便查看，但输出到文件时，加颜色就没有必要了
  pattern: 
    console: "%d{HH:mm:ss} [%thread] %-5level (%file:%line\\) - %msg %n"
  #  file: "[%thread] %-5level %d{HH:mm:ss} %class{16}:%line - %msg %n"
  #file.name: target/logs.txt
     
wechat:
  url:
    entry:      "https://wx.qq.com/"
    login_base: "https://login.weixin.qq.com"
    path_base:  "/cgi-bin/mmwebwx-bin"
    uuid:       "${wechat.url.login_base}/jslogin?appid=wx782c26e4c19acffb&fun=new&lang=zh_CN&_=%s&redirect_uri=https%3A%2F%2Fwx.qq.com%2Fcgi-bin%2Fmmwebwx-bin%2Fwebwxnewloginpage%3Fmod%3Ddesktop"
    qrcode:     "${wechat.url.login_base}/qrcode"
    login:      "${wechat.url.login_base}${wechat.url.path_base}/login?loginicon=true&uuid=%s&tip=0&r=%s&_=%s"
    init:       "%s${wechat.url.path_base}/webwxinit?r=%s"
    statreport: "${wechat.url.entry}${wechat.url.path_base}/webwxstatreport?fun=new"
    status_notify: "%s${wechat.url.path_base}/webwxstatusnotify"
    sync_check: "%s${wechat.url.path_base}/synccheck"
    sync:       "%s${wechat.url.path_base}/webwxsync?sid=%s&skey=%s"
    get_contact: "%s${wechat.url.path_base}/webwxgetcontact?r=%s&seq=%s&skey=%s"
    send_msg:   "%s${wechat.url.path_base}/webwxsendmsg"
    upload_media: "%s${wechat.url.path_base}/webwxuploadmedia?f=json"
    get_msg_img: "%s${wechat.url.path_base}/webwxgetmsgimg?&MsgID=%s&skey=%s"
    get_voice:   "%s${wechat.url.path_base}/webwxgetvoice"
    get_video:   "%s${wechat.url.path_base}/webwxgetvideo"
    push_login:  "%s${wechat.url.path_base}/webwxpushloginurl"
    logout:      "%s${wechat.url.path_base}/webwxlogout?redirect=1&type=1&skey=%s"
    batch_get_contact: "%s${wechat.url.path_base}/webwxbatchgetcontact?type=ex&r=%s"
    op_log:      "%s${wechat.url.path_base}/webwxoplog"
    verify_user: "%s${wechat.url.path_base}/webwxverifyuser"
    get_media:   "%s${wechat.url.path_base}/webwxgetmedia"
    create_chatroom: "%s${wechat.url.path_base}/webwxcreatechatroom?r=%s"
    delete_chatroom_member: "%s${wechat.url.path_base}/webwxupdatechatroom?fun=delmember"
    add_chatroom_member: "%s${wechat.url.path_base}/webwxupdatechatroom?fun=addmember"


jeeves:
  instance-id: jeeves
  auto-relogin-when-qrcode-expired: true
  max-qr-refresh-times: 5

